[package]
name = "markterm-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
markterm = { path = "../markterm" }

[[bin]]
name = "markterm"
path = "src/main.rs"

doc = false