name: Continuous Integration
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    name: Run all tests
    env:
      CLICOLOR_FORCE: 1
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
        toolchain: [ stable ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy
      - name: Check project
        run: cargo check
      - name: Run clippy
        run: cargo clippy -- --deny warnings
      - name: Run tests on markdown
        run: cargo test