name: Continuous Integration
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  fmt:
    name: RustFmt
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt
      - run: cargo fmt --all -- --check
  clippy:
    name: Run clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
  test:
    name: Run all tests
    env:
      CLICOLOR_FORCE: 1
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
        toolchain: [ stable ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy
      - name: Check project
        run: cargo check
      - name: Run clippy
        run: cargo clippy -- --deny warnings
      - name: Run tests on markdown
        run: cargo test